### ISSUE TITLE
Please add a LICENSE file

### ISSUE THREAD

**Issue by mithro** [westonb/open-pmic#1]
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by westonb** [comment]
Thanks for the reminder!

Added in https://github.com/westonb/open-pmic/commit/9f616459827b5ca0565903c2c924ba74b4a80395#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7
